# @package _global_
dataset_name: two_ends_R_S.C.-sylv._Track_0_80_icbm09c
data_dir: ${dataset_folder}/R_S.C.-sylv._crops_two_ends_R_S.C.-sylv._Track_0_80_icbm09c.npy
subject_dir: ${dataset_folder}/R_S.C.-sylv._subjects.csv
in_shape: [1, 84, 68, 98]
subjects_to_remove: null
remove_subjects: false
train_list: null
validation_list: null
